### ISSUE TITLE
Significant discrepancies in GHA and DEC for planets up to 2050 identified

### ISSUE THREAD

**Issue by aendie** [brandon-rhodes/pyephem#220]
Greetings!
I decided to check Skyfield data against Ephem data for the years 2021 to 2050. I checked the GHA and Declination of the Sun, Moon and navigational planets for every hour on every day using Skyfield as a reference. This was done programmatically, of course, with some "data mining" to pull values out of the (identically formatted) TeX files I had created when generating all Nautical Almanacs up to and including 2050.

Generally the conformity was excellent with typically only ±0°00.1’ deviation (comparing the _rounded_ figures, as printed). Even ±0°00.2’ deviation is unusual. This shows **excellent agreement with Skyfield** (= NASA JPL HORIZONS System). The Sun and Moon positions are perfect.

However I also identified strange inconsistencies in (navigational) planet positions. I am aware that Ephem is based on XEphem, which I believe still uses VSOP87D for the planets. And there have been numerous updates to it: VSOP2000, VSOP2002, VSOP2010, VSOP2013. So my questions are:

- can you confirm these deviations? (so that it's not just my code that shows them)
- can this problem be traced back to Ephem?
- or is it a "feature" (rather than a "bug") in VSOP87D?

I'm not asking for a bugfix (unless it's easy and obvious) - I'm just highlighting a discrepancy that I was unaware of until I began computerized cross-checking of every GHA and Declination in my almanacs.

The crazy figures are very rare and only affect one specific hour, with the deviation slowly returning back to normal over the next day or two. Something “kicks” the value sky high. The worst case is from 2036 (Jupiter GHA deviation -0°48.0’ and DEC deviation -0°43.5’):

![2036 delta](https://user-images.githubusercontent.com/13238632/142931080-1864529b-c498-4772-9770-2804d260daf8.JPG)

The second worst case is this from 2024 (Jupiter GHA deviation 0°37.1’ and DEC deviation -0°20.7’):

![2024 delta](https://user-images.githubusercontent.com/13238632/142931230-5d424ea5-fdd6-4819-95c9-da66d4781616.JPG)

But other planets are also “kicked” out of their orbits:

- Saturn at 14h on 20th March 2030
- Mars at 2h on 20th March 2032 (deviations only 0°03.0’ GHA and 0°01.1’ DEC but it's still a sudden deviation)
- Jupiter at 23h on 19th March 2048 (sudden deviation of -0°04.7’ GHA)
- Mars at 5h on 20th March 2049 (deviations only -0°02.0’ GHA and 0°00.7’ DEC)

### What happens on 20th March 2036 (in Ephem)?

Looking closer at the case from 2036: on 19th March the GHA deviation at 20h is only -0°00.1’ and at 21h, 22h, 23h and 00h on 20th it is ZERO (comparing _rounded_ data). 
Then the bombshell hits at 01h (probably some minutes earlier).
Then you see how the GHA and DEC deviations slowly diminish after the "jolt" at 01h.

I have a python program (attached below) that can be used to quickly generate RA, GHA and Declination for all hours on one day in a format very similar to NASA JPL HORIZONS System. The above example displays thus:

![20-03-2036 Jupiter](https://user-images.githubusercontent.com/13238632/142934219-f0a566ed-d71f-431b-be54-bcaa0f158ddb.JPG)

The program below wins no "pythonic" points (I hacked it out quickly), but I think it could be a useful tool anyway.
All correspondence on this topic will be highly appreciated!

[cmp_Ephem.zip](https://github.com/brandon-rhodes/pyephem/files/7584349/cmp_Ephem.zip)

**Comment by brandon-rhodes** [comment]
That’s a good question! I wrote a quick program to look at Jupiter’s behavior over that hour or two:
```
import ephem

body = ephem.Jupiter()

for h in range(2):
    for m in range(0, 60, 5):
        d = ephem.Date(f'2036-03-20 {h}:{m}')
        body.compute(d)
        print(d, body.a_ra, body.g_ra)
```
And then I re-ran that program repeatedly, while festooning `circum.c` with `printf()` calls and rebuilding and rerunning. I was intrigued to see that astrometric RA was unaffected, but geocentric RA was going haywire. Here’s a diff showing the calls I wound up with when I was finished:
```
diff --git libastro/circum.c libastro/circum.c
index 9b6aa0c..37e5307 100644
--- libastro/circum.c
+++ libastro/circum.c
@@ -702,14 +702,20 @@ Obj *op)  /* object to set s_ra/dec as per equinox */
        /* allow for relativistic light bending near the sun.
         * (avoid calling deflect() for the sun itself).
         */
+       printf("%.6f ", ra);  /* good here */
+       fflush(stdout);
+
        if (!is_planet(op,SUN) && !is_planet(op,MOON))
            deflect (mjed, op->s_hlong, op->s_hlat, lsn, rsn, *rho, &ra, &dec);
 
+       printf("%.6f ", ra);  /* bad here */
+       fflush(stdout);
+
        /* correct ra/dec to form geocentric apparent */
        nut_eq (mjed, &ra, &dec);
        if (!is_planet(op,MOON))
            ab_eq (mjed, lsn, &ra, &dec);
-       op->s_gaera = ra;
+       op->s_gaera = ra;  /* bad */
        op->s_gaedec = dec;
 
        /* find parallax correction for equatoreal coords */
@@ -815,6 +821,8 @@ double *ra, double *dec)/* geocentric equatoreal */
         *              g1 is always about 0.004 arc seconds
         *              g2 varies from 0 (highest contribution) to 2
         */
+       printf("%d ", rho<rsn);
+       fflush(stdout);
        if (el<degrad(170) || el>degrad(179.75) || rho<rsn) return;
 
        /* get cartesian vectors */
```
And the output:
```
0.815652 1 0.815652 2036/3/20 00:00:00 3:04:54.17 3:06:54.58
0.815663 1 0.815663 2036/3/20 00:05:00 3:04:54.33 3:06:54.74
0.815675 1 0.815675 2036/3/20 00:10:00 3:04:54.49 3:06:54.90
0.815687 1 0.815687 2036/3/20 00:15:00 3:04:54.65 3:06:55.06
0.815698 1 0.815698 2036/3/20 00:20:00 3:04:54.81 3:06:55.22
0.815710 1 0.815710 2036/3/20 00:25:00 3:04:54.97 3:06:55.38
0.815722 1 0.815722 2036/3/20 00:30:00 3:04:55.13 3:06:55.54
0.815733 1 0.815733 2036/3/20 00:35:00 3:04:55.29 3:06:55.70
0.815745 1 0.815745 2036/3/20 00:40:00 3:04:55.45 3:06:55.87
0.815757 1 0.815757 2036/3/20 00:45:00 3:04:55.61 3:06:56.03
0.815769 1 0.815769 2036/3/20 00:50:00 3:04:55.77 3:06:56.19
0.815780 0 0.844323 2036/3/20 00:55:00 3:04:55.93 3:13:28.86
0.815792 0 0.829743 2036/3/20 01:00:00 3:04:56.09 3:10:08.36
0.815804 0 0.825035 2036/3/20 01:05:00 3:04:56.25 3:09:03.62
0.815815 0 0.822714 2036/3/20 01:10:00 3:04:56.41 3:08:31.70
0.815827 0 0.821334 2036/3/20 01:15:00 3:04:56.58 3:08:12.72
0.815839 0 0.820421 2036/3/20 01:20:00 3:04:56.74 3:08:00.17
0.815850 0 0.819774 2036/3/20 01:25:00 3:04:56.90 3:07:51.28
0.815862 0 0.819293 2036/3/20 01:30:00 3:04:57.06 3:07:44.66
0.815874 0 0.818922 2036/3/20 01:35:00 3:04:57.22 3:07:39.55
0.815886 0 0.818628 2036/3/20 01:40:00 3:04:57.38 3:07:35.51
0.815897 0 0.818389 2036/3/20 01:45:00 3:04:57.54 3:07:32.23
0.815909 0 0.818193 2036/3/20 01:50:00 3:04:57.70 3:07:29.52
0.815921 0 0.818028 2036/3/20 01:55:00 3:04:57.86 3:07:27.26
```
So it looks like the `rho<rsn` decision, which is supposed to be the condition “is the distance to the planet less than the distance to the Sun”, is flipping from `1` true to `0` false and turning off the deflection calculation.

But how can that make sense? Adding another `printf()`, this is at a moment when the elongation is `178.96`, which isn't a moment when I would expect Jupiter and the Sun to be at the same distance.

In any case, the immediate answer is that the `libastro` library that powers PyEphem is turning off deflection at an inopportune moment.

I don’t suppose you’d have time to track down which number is going wrong in C code? :slightly_smiling_face:

**Comment by brandon-rhodes** [comment]
Oh.

Look at that.

The call to `deflect()` says:

```
	    deflect (mjed, op->s_hlong, op->s_hlat, lsn, rsn, *rho, &ra, &dec);
```
But the function definition is:
```
static void
deflect (
double mjd1,		/* equinox */
double lpd, double psi,	/* heliocentric ecliptical long / lat */
double rsn, double lsn,	/* distance and longitude of sun */
double rho,		/* geocentric distance */
double *ra, double *dec)/* geocentric equatoreal */
```
So it's receiving `lsn, rsn` but assigning those to parameters `rsn, lsn` which are swapped and in the opposite order. So instead of comparing the distances of Jupiter and the Sun, it's comparing the distance to Jupiter in AU to the Sun's elongation in radians. When the latter value loops around from 2𝜋 = 6.28 and back to 0.0, then suddenly the effect of deflection — if it happens to be activated — turns on and the planet makes a jump across the sky.

I'll see if making the fix breaks any tests!

**Comment by brandon-rhodes** [comment]
All right, I've committed:

f7ff8c4a156df9c4cb1ab23c97e99742eacfa88c

—which might fix the problem. If you could try installing the developer version:
```
pip install -U https://github.com/brandon-rhodes/pyephem/archive/master.zip
```
—then I'll be interested to hear whether you see any improvement. Thanks for letting me know about the misbehavior!

**Comment by aendie** [comment]
Brilliant! You are a genius!
All cases I identified are perfect now.
Comparing the "worst" case I found (above) on 20th March 2036, it now looks very good:

![20-03-2036 JupiterOK](https://user-images.githubusercontent.com/13238632/143047477-d8ff3a95-3a61-4b98-896d-5c79bf79a585.JPG)

I still can't believe you found the problem so quickly.
You adhere to the motto "the difficult I fix immediately; the impossible takes a bit longer".
Many thanks ... I look forward to the release of Ephem 4.2

**Comment by aendie** [comment]
Ah ... just a question: most "good" figures for a year look like this:

![image](https://user-images.githubusercontent.com/13238632/143061212-f39e4e40-5c48-4ff7-921d-afdd560de19d.png)

In other words, as I originally mentioned the deviation is typically only ±0°00.1’ (comparing the _rounded_ figures, as printed). Occasionally ±0°00.2’ deviation is seen. I take this to be the normal case now as Ephem and Skyfield **agree exceptionally well**.

Now that I have recreated all nautical almanacs (using my Pyalmanac), I am comparing every year from 2020 to 2050 once again.

Only this one year has discrepancies above ±0°00.2’:

![image](https://user-images.githubusercontent.com/13238632/143062864-fcd350dc-6597-4b6d-b6db-4cc546667a6b.png)

This is very minor indeed, nevertheless I took a closer look. Here is Jupiter on 01-01-2032:

![image](https://user-images.githubusercontent.com/13238632/143063984-3a8e3910-f800-441f-b0e0-3d3842a4e801.png)

So Jupiter "takes a little ride" at 8 AM (maybe when the alarm clock goes off on New Years Day).
It just looks "a little strange" when just about every other value is within ±0°00.1’.
I haven't checked yet with HORIZONS, which data is better (Ephem or Skyfield).

Your honored opinion is most welcome (and, if you see fit - I could create a new Issue).

**Comment by brandon-rhodes** [comment]
Are the moments happening when Jupiter is passing the Sun? I noted in the code there were a few comments:
```
	/* only continue if object is within about 10 deg around the sun,
	 * not obscured by the sun's disc (radius 0.25 deg) and farther away
	 * than the sun.
	 *
	 * precise geocentric deflection is:  g1 * tan(el/2)
	 *	radially outwards from sun;  the vector munching below
	 *	just applys this component-wise
	 *	Note:	el = HELIOCENTRIC elongation.
	 *		g1 is always about 0.004 arc seconds
	 *		g2 varies from 0 (highest contribution) to 2
	 */
	if (el<degrad(170) || el>degrad(179.75) || rho<rsn) return;
```
So it looks like the moment a planet goes behind the sun, "libastro" turns off deflection. Maybe you're noticing the moments where the deflection effect snaps on or off?

**Comment by aendie** [comment]
Yes... here is data for the Sun:

![image](https://user-images.githubusercontent.com/13238632/143066846-f8a40e6c-ad99-44ad-9b2d-d0f2dad33190.png)

**Comment by brandon-rhodes** [comment]
If the Sun is indeed coming very close to Jupiter (which you could also confirm by computing their angular separation) then I think we can squarely blame the above deflection code. Do you know what HORIZONS chooses to do with deflection when a planet goes behind the disc of the Sun itself?

**Comment by aendie** [comment]
I agree with you. I do not know what HORIZONS does in this case. The effect is so minimal, I can easily ignore it. Ephem, for those who want the speed of calculations, is excellent. I prefer Skyfield, as it is well designed and provides high accuracy where needed.

Feel free to close this case. Again, my utmost thanks for your assistance!

**Comment by brandon-rhodes** [comment]
I've just released PyEphem 4.1.1 with this fix. Thanks again for uncovering it!
